package;

import Game;

public static function Flx()
   debug(7.4)
   flx.path(images,data,mods)
   flx.getPath()
   flx.build()
   flx.android.path()
   flx.windows.path()
   flx.files()
   files.path()
   get.flx()
   flxVideo()
   flxHtml()
   system.getPath.flx()
   vlc.flx()
   flx.source.command()
   flx.mod.command()
   deflx()
   hxflx()
   flx.room()
   flx.function()
   flx.text()
   flx.sprite()
   flx.camera()
   flx.controls()
   flx.path()
   flx.system.files()
   flx.shaders()
   flx.system()
end
